syncfusion-content/flutter-docs

Flutter/cartesian-charts/chart-types/error-bar-chart.md
Flutter/cartesian-charts/series-customization.md

API link added for Errorbar chart and animation dealy.

FLUT-6158 - [Others] API link added for Errorbar chart and animation dealy.

---

Flutter/cartesian-charts/getting-started.md

Updated code snippet in flutter cartesian chart getting started.

FLUT-6259- [Bug] Updated code snippet content in flutter charts.

---

Flutter/cartesian-charts/multiple-charts.md

Add data source for multiple series in flutter cartesian charts.

FLUT-6089 - [Others] Add datasource for multiple series

---

Flutter/xlsio/worksheet-rows-and-columns-manipulation.md

Hi @johnsonmonohar ,
Regards,
Keerthi.

FLUT-6317-[documentation][flutter]: Hide Rows And Columns - XlsIO

---

Flutter/datagrid/columns-resizing.md
Flutter/datagrid/freeze-panes.md

- Added DataGrid theme details in the UG documentation.

FLUT-6321 - [Feature] Added the DataGrid Theme details in the UG documentation 

---

Flutter/cartesian-charts/chart-types/area-chart.md

Added see Also [color palette] and [color mapping] links for testing

FLUT-6290 - [Others] Added link for testing

---

Flutter/cartesian-charts/chart-types/scatter-chart.md

* Have resolved the below customer bug: [369403](https://support.syncfusion.com/agent/tickets/369403).

FLUT-6290 - [Others] Customer Bug fixed 

---

Flutter/pdf-viewer/overview.md

Added windows support in overview page.

FLUT-5235 - Added windows support in overview

---

Flutter/cartesian-charts/chart-types/scatter-chart.md

* Have resolved the below customer bug: [369403](https://support.syncfusion.com/agent/tickets/369403).

FLUT-6158 - [Others] Customer Bug fixed 

---

Flutter/xlsio/working-with-excel-worksheet.md

Kindly review the content and let me know your feedback.
Regards,
Keerthi.

FLUT-6285-[documentation][flutter]: RTL

---

flutter-toc.html

Fixed the localization live refreshing issue which was made by improper toc file changes.

FLUT-6406 - [Others] Fixed the localization page live issue

---

Flutter/xlsio/working-with-image.md

Kindly review and merge the changes,
Regards,
Keerthi.

FLUT-6410-[documentation][flutter]: Modify Code

---

Flutter/datagrid/row-height-customization.md

* We have updated the row height code snippet based on the output image.

FLUT-6409 - [Feature] Updated the data grid documentation.

---

Flutter/cartesian-charts/chart-types/stacked-bar-chart.md
Flutter/cartesian-charts/chart-types/stacked-column-chart.md

Resolve the below issue.
http://helpstaging.syncfusion.com:14038/error/03-25-2022/17/flutter.txt

FLUT-6290 - [Others] Resolve the  error log issue in staging.

---

Flutter/DateRangePicker/Callbacks.md
Flutter/DateRangePicker/views.md
Flutter/calendar/appointments.md
Flutter/calendar/timeslot-views.md

I have added an API link to the calendar.

FLUT-6329- [Feature] UG document for calendar

---

Flutter/cartesian-charts/localization.md
Flutter/globalization.md

Added content about the newly added languages norwegian and oriya.

FLUT-6439 - [Others] Added two new supported languages

---

Flutter/cartesian-charts/export-cartesian-chart.md
Flutter/circular-charts/export-circular-chart.md

The previous codes which are available in chart exporting files are wrong. Those were replaced with proper code snippets now.

FLUT-6454 - [Others] Changed the chart exporting file codes

---

Flutter/DateRangePicker/Callbacks.md
Flutter/DateRangePicker/builders.md
Flutter/DateRangePicker/customizations.md
Flutter/DateRangePicker/date-navigations.md
Flutter/DateRangePicker/date-restrictions.md
Flutter/DateRangePicker/getting-started.md
Flutter/DateRangePicker/headers.md
Flutter/DateRangePicker/localization.md
Flutter/DateRangePicker/right-to-left.md
Flutter/DateRangePicker/selections.md
Flutter/DateRangePicker/views.md
Flutter/calendar/appointment-resizing.md
Flutter/calendar/appointments.md
Flutter/calendar/builders.md
Flutter/calendar/callbacks.md
Flutter/calendar/date-navigations.md
Flutter/calendar/getting-started.md
Flutter/calendar/headers.md
Flutter/calendar/load-more.md
Flutter/calendar/localization.md
Flutter/calendar/month-view.md
Flutter/calendar/resource-view.md
Flutter/calendar/right-to-left.md
Flutter/calendar/schedule-view.md
Flutter/calendar/timeslot-views.md

Hi @Sasikumar3595,
UG documentation updated as per the guideline. Following is applicable for our  control.
Support for Customized Code Tab Names 
Support for highlighting specific lines in the code block
Kindly review and share your suggestions.
Regards,
Indumathi R

FLUT-6541-UGDocument-Document updated as per the guidelines.

---

Flutter/DateRangePicker/date-navigations.md

FLUT-6541-UGDocument-API links updated.

---

flutter-toc.html

Resolved the issue in toc.html.

FLUT-6392 - [Others] Resolved the issue in toc.html.

---

flutter-toc.html

FLUT-6392 - [Others] Resolved the conflicts in UG.

---

Flutter/DateRangePicker/Callbacks.md
Flutter/DateRangePicker/builders.md
Flutter/DateRangePicker/customizations.md
Flutter/DateRangePicker/date-navigations.md
Flutter/DateRangePicker/date-restrictions.md
Flutter/DateRangePicker/headers.md
Flutter/DateRangePicker/hijri-date-picker.md
Flutter/DateRangePicker/localization.md
Flutter/DateRangePicker/right-to-left.md
Flutter/DateRangePicker/selections.md
Flutter/DateRangePicker/views.md
Flutter/calendar/appointments.md
Flutter/calendar/builders.md
Flutter/calendar/callbacks.md
Flutter/calendar/drag-drop.md
Flutter/calendar/getting-started.md
Flutter/calendar/load-more.md
Flutter/calendar/month-view.md
Flutter/calendar/resource-view.md
Flutter/calendar/right-to-left.md
Flutter/calendar/schedule-view.md
Flutter/calendar/timeslot-views.md
Flutter/calendar/timezone.md

Important properties high lighted.

FLUT-6541-UGDevelopment-Important properties high lighted.

---

Flutter/calendar/builders.md

FLUT-6541-UGDevelopment-Missing symbol added.

---

Flutter/DateRangePicker/getting-started.md
Flutter/calendar/appointment-resizing.md
Flutter/calendar/builders.md
Flutter/calendar/right-to-left.md

Missing properties highlighted.

FLUT-6541-HighLightFlutterUG-Missing properties highlighted.

---

Flutter/xlsio/working-with-cells.md
Flutter/xlsio/working-with-data-validation.md
Flutter/xlsio/working-with-table.md

FLUT-6674-[documentation][flutter]: Auto Filters

---

Flutter/DateRangePicker/builders.md
Flutter/DateRangePicker/headers.md
Flutter/calendar/month-view.md

FLUT-6541-HighLightFlutterUG-Missing changes added.

---

Flutter/installation-and-upgrade/system-requirements.md

Changed version changes in the user guide since our widgets support to the latest version.

FLUT-6666 - [Others] Modified version changes in userGuide

---

Flutter/datagrid/export-to-pdf.md

- Changed pdf save method to saveSync in datagrid `export to pdf` document

FLUT-6235 - [Others] Changed the pdf save method name to saveSync 

---

Flutter/installation/mac-installer/how-to-install.md

IN-18200-UG-Documentation-flutter-hotfix

---

Flutter/xlsio/working-with-excel-worksheet.md

FLUT-6850 - UG documentation for worksheet tab color - Development

---

Flutter/xlsio/working-with-excel-worksheet.md

FLUT-6849 - UG documentation to hide Excel worksheet - Development

---

Flutter/xlsio/working-with-excel-worksheet.md

FLUT-6814 - UG documentation for Save as CSV support - Development

---

Flutter/xlsio/working-with-excel-worksheet.md

FLUT-6883 - UG documentation for moving worksheets using flutter XlsIO - Development

---

Flutter/system-requirements.md

* Updated Flutter stable version as 3.3.2 and also removed the beta version from the UG documentation.

FLUT-6909 - [Others] Updated latest flutter stable version and removed the beta version

---

Flutter/pdf-viewer/getting-started.md
Flutter/pdf-viewer/overview.md
Flutter/pdf-viewer/text-search.md

* Updated the UG content for text search asynchronous support.

FLUT-6919 - [Others] Updated UG content for text search asynchronous support

---

Flutter/xlsio/working-with-charts.md

FLUT-6921 - Package Name - XlsIO - HF

---

Flutter/datagrid/editing.md
Flutter/datagrid/sorting.md

* We have adapted the content review changes in the data grid volume 3 (sorting and editing) UG documentation.

FLUT-6853 - [Feature] Modified the content review changes in the data grid volume 3 UG documentation

---

Flutter/datagrid/filtering.md

* We have already provided the UG documentation for our new filtering feature in flutter data grid control.
* Here, we have ensured the documentation changes in the staging site and resolved the alignment issues in the documentation.

FLUT-6128 - [Others] Resolved the alignment issues in the filtering UG documentation

---

Flutter/datagrid/filtering.md

* API links have been provided to the new filtering UG documentation.
* Resolved the alignment issues.

FLUT-6128 - [Others] API reference links have been provided to the filtering UG

---

Flutter/datagrid/selection.md

- Provided the API Link to the `rows` property in the Selection UG documentation.

FLUT-6970 - [Others] - Provided the API Link in the Selection UG documentation

---

Flutter/cartesian-charts/export-cartesian-chart.md
Flutter/circular-charts/export-circular-chart.md
Flutter/funnel-chart/export-funnel-chart.md
Flutter/pyramid-chart/export-pyramid-chart.md

**Description:**
- Resolved the incorrect code snippet provided in the export to pdf user guide documentation section in the cartesian and circular charts.

FLUT-6833 - [Bug] Resolved incorrect code snippet of export to pdf user guide documentation in flutter charts

---

Flutter/xlsio/working-with-excel-worksheet.md

Kindly review and merge the changes.
Regards,
Keerthi.

FLUT-7009-NamedRangeXlsIO-Dev

---

Flutter/xlsio/working-with-excel-worksheet.md

Kindly review and merge the changes.
Regards,
Keerthi.

FLUT-6942-FreezePanesXlsIO-Dev

---

Flutter/xlsio/working-with-excel-worksheet.md

Kindly review and merge the changes.
Regards,
Keerthi.

FLUT-6940-PageSetupXlsIO-Dev

---

Flutter/introduction/overview.md

Description:
* Removed iOS link.

FLUT-7162 - [Bug] Removed iOS link

---

Flutter/datagrid/column-types.md
Flutter/datagrid/sorting.md

* UG documentation content for DataGrid `sort order number and its background color change` and `checkbox shape change` topics has been modified.

FLUT-7154 - [Feature] The content has been modified in the sorting number style and checkbox shape DataGrid topics.

---

Flutter/datagrid/filtering.md

* UG documentation content for DataGrid `sort order number and its background color change` and `checkbox shape change` topics has been modified.

FLUT-7154 - [Feature] The content has been modified in the filter popup menu customizing DataGrid topic.

---

Flutter/cartesian-charts/chart-types/bar-chart.md
Flutter/cartesian-charts/chart-types/scatter-chart.md
Flutter/cartesian-charts/chart-types/stacked-bar-100-chart.md
Flutter/cartesian-charts/chart-types/step-line-chart.md
Flutter/slider/tooltip.md
Flutter/system-requirement-installation/system-requirements.md

* Added the data source information in the code snippet in the chart.
* Added the import detail in the slider tooltip.
* Added note for PDF didn't have support in Linux.

FLUT-7196 - [Others] Added the data source information, import details and note

---

Flutter/cartesian-charts/getting-started.md
Flutter/cartesian-charts/methods.md
Flutter/radial-gauge/getting-started.md

Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman

SEO-3146-coverage-page-with-redirect-help

---

Flutter/system-requirements.md

* Added the PDF control is not support the Linux platform.

FLUT-7196 - [Others] Added notes for PDF control supported platform related information

---

Flutter/datagrid/columns-resizing.md

I have included the content and sample code for the resizing column is a checkbox column or not.

FLUT-7197 - [Others] UG for the resizing column is a checkbox column or not.

---

Flutter/system-requirements.md

* Added the latest SDK version.

FLUT-7196 - [Others] Updated SDK

---

Flutter/pdf-viewer/magnification.md

I have included the content and sample code for the maxzoollevel feature.

FLUT-7403 - [Others] UG for the maxzoomlevel feature . 

---

Flutter/datagrid/editing.md
Flutter/datagrid/filtering.md
Flutter/datagrid/sorting.md

I have modified the content based on the content review for  UG of completed feature.

FLUT-4956 - [Others] UG Documentation changes in content review.

---

Flutter/datagrid/editing.md
Flutter/datagrid/filtering.md
Flutter/datagrid/sorting.md

I have add the API links for the completed UG documents.

FLUT-4956 - [Others] Adding API for completed UG document.

---

Flutter/signaturepad/overview.md

Hi @Aishwarya-Ganesan,
Worked on SEMrush report issues, so merge these changes
Regards,
Gowthaman

SEO-3439-semrush-report-issues

---

Flutter/range-slider/enabled-and-disabled-state.md
Flutter/slider/enabled-and-disabled-state.md

* Modified the incorrect code snippet to the correct form in the slider and range slider control.
https://support.syncfusion.com/agent/tickets/451109

FLUT-7436 - [Others] Modified the incorrect code snippet to proper

---

Flutter/datagrid/getting-started.md

* The DataGrid sample source code has been added to the Getting Started topic.

FLUT-7436 - [Others] DataGrid sample source code has been added.

---

Flutter/pdf/working-with-annotations.md

Hi All,
Updated all annotation set Appearance property is true for visible purpose.
Regards,
Sameerkhan N

830575 Updated the annotation set Appearance is true for visible purpose.

---

Flutter/DateRangePicker/builders.md
Flutter/DateRangePicker/customizations.md
Flutter/DateRangePicker/date-navigations.md
Flutter/DateRangePicker/date-restrictions.md
Flutter/DateRangePicker/getting-started.md
Flutter/DateRangePicker/headers.md
Flutter/DateRangePicker/hijri-date-picker.md
Flutter/DateRangePicker/selections.md
Flutter/DateRangePicker/views.md
Flutter/circular-charts/callbacks.md
Flutter/circular-charts/circular-series-customization.md
Flutter/circular-charts/getting-started.md
Flutter/circular-charts/selection.md
Flutter/datagrid/getting-started.md
Flutter/funnel-chart/getting-started.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-Flutter-redirection-tool-fixes-1

---

Flutter/installation/Installation-errors.md
Flutter/installation/offline-installer/how-to-download.md
Flutter/installation/offline-installer/how-to-install.md
Flutter/installation/web-installer/how-to-download.md
Flutter/installation/web-installer/how-to-install.md
Flutter/linear-gauge/getting-started.md
Flutter/maps/getting-started.md
Flutter/maps/tile-layer.md
Flutter/pdf-viewer/How-to/Resolve-Library-not-loaded-rpath-libswiftCore-dylib-error.md
Flutter/pdf-viewer/getting-started.md
Flutter/pdf/getting-started.md
Flutter/pyramid-chart/getting-started.md
Flutter/range-selector/getting-started.md
Flutter/range-slider/getting-started.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-Flutter-redirection-tool-fixes-2

---

Flutter/Upgrade/Upgrade-from-major-version-to-service-pack-version.md
Flutter/Upgrade/Upgrade-from-one-version-to-another-version.md
Flutter/Upgrade/how-to-upgrade.md
Flutter/signaturepad/getting-started.md
Flutter/sparkcharts/getting-started.md
Flutter/sparkcharts/sparkcharts-types.md
Flutter/system-requirement-installation/system-requirements.md
Flutter/system-requirements.md
Flutter/treemap/getting-started.md
Flutter/xlsio/getting-started.md
Flutter/xlsio/security.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-Flutter-redirection-tool-fixes-3

---

Flutter/system-requirements.md

* Added the latest SDK version.

FLUT-831773 - [Others] Updated SDK

---

Flutter/calendar/date-navigations.md

- Calendar UG updated in Flutter
- Added new topic for Show today button in Calendar UG

FLUT-Development-Calendar UG updated

---

Flutter/system-requirements.md

FLUT-831038 Updated the android minimum api level in ug

FLUT-831038 Updated the android minimum api level in ug

---

Flutter/pdf-viewer/form-filling.md
Flutter/pdf-viewer/getting-started.md
flutter-toc.html

* Added UG for the form filling support.

FLUT-827676 - [Others] Added UG for the form filling support

---

Flutter/Licensing/overview.md

* Moved License related ug details to Flutter page.

FLUT-831038 - [Others] Moved license related ug details to flutter page

---

Flutter/datagrid/accessibility.md
Flutter/datagrid/column-drag-and-drop.md
Flutter/datagrid/column-types.md
Flutter/datagrid/columns-resizing.md
Flutter/datagrid/columns-sizing.md
Flutter/datagrid/conditional-styling.md
Flutter/datagrid/data-binding.md
Flutter/datagrid/editing.md
Flutter/datagrid/export-to-excel.md
Flutter/datagrid/export-to-pdf.md
Flutter/datagrid/filtering.md
Flutter/datagrid/footer.md
Flutter/datagrid/freeze-panes.md
Flutter/datagrid/getting-started.md
Flutter/datagrid/localization.md
Flutter/datagrid/overview.md
Flutter/datagrid/paging.md
Flutter/datagrid/pull-to-refresh.md
Flutter/datagrid/right-to-left.md
Flutter/datagrid/row-height-customization.md
Flutter/datagrid/scrolling.md
Flutter/datagrid/selection.md
Flutter/datagrid/sorting.md
Flutter/datagrid/stacked-headers.md
Flutter/datagrid/styles.md
Flutter/datagrid/summaries.md
Flutter/datagrid/swiping.md

* I have updated the Flutter DataGrid UG.

FLUT-829266 - [Others] Updated the Flutter DataGrid document.

---

Flutter/datagrid/overview.md

- I have added the features description in the DataGrid overview file.

FLUT-7437 - [Others] The features description has been added in the DataGrid overview file.

---

Flutter/datagrid/overview.md

- I have added the features description in the DataGrid overview file.

FLUT-829266 - [Others] The features description has been added in the DataGrid overview file.

---

Flutter/pdf-viewer/accessibility.md
Flutter/pdf-viewer/form-filling.md
Flutter/pdf-viewer/gesture-callbacks.md
Flutter/pdf-viewer/getting-started.md
Flutter/pdf-viewer/hyperlink-navigation.md
Flutter/pdf-viewer/right-to-left.md
Flutter/pdf-viewer/text-search.md
Flutter/pdf-viewer/text-selection.md
flutter-toc.html

* Added UG for the programmatic, callback and read-only support for form fields.
* Added UG for onTap callback support.

FLUT-839471 - [Others] Added UG for the programmatic and callback support for form fields and onTap callback support.

---

Flutter/installation/mac-installer/how-to-download.md

Hi @Aishwarya-Ganesan,
Have worked on Flutter Page with Redirect, please review.
Regards,
Yvone.

SEO-174775 Flutter Page with Redirect

---

Flutter/circular-charts/getting-started.md

* Removed the unwanted color property which has been given as optional parameter in the bind data source topic at getting started section in the SfCircularChart.

FLUT-838230 - [Others] Remove color in getting started at circular charts

---

Flutter/pdf-viewer/form-filling.md
Flutter/pdf-viewer/gesture-callbacks.md
Flutter/pdf-viewer/overview.md

Added the use case code snippets in pdf viewer -> form filling section

FLUT-839471 - [Others] Add use case code snippets

---

Flutter/pdf-viewer/form-filling.md
Flutter/pdf-viewer/gesture-callbacks.md

Addressed the content review feedback in https://github.com/syncfusion-content/flutter-docs/pull/641

FLUT-839471 - [Others] Address content review feedback

---

Flutter/pdf-viewer/How-to/Resolve-Library-not-loaded-rpath-libswiftCore-dylib-error.md
Flutter/pdf-viewer/form-filling.md

Resolved the below publishing failed issue.
http://help.syncfusion.com/Error/09-14-2023/18/Flutter.txt

FLUT-846573 - [Others] Resolved the publishing failed issue .

---

Flutter/datagrid/column-types.md

- I have add the API links for the completed UG documents.

FLUT-833441 - [Others] Added API link for completed features

---

Flutter/datagrid/column-types.md

- I have add the changes for the completed UG documents.

FLUT-848451- [Others] UG Changes for the ShowColumnHeaderIconOnHover feature

---

Flutter/funnel-chart/callbacks.md
Flutter/funnel-chart/chart-appearance.md
Flutter/funnel-chart/export-funnel-chart.md
Flutter/funnel-chart/funnel-customization.md
Flutter/funnel-chart/methods.md
Flutter/funnel-chart/right-to-left.md
Flutter/funnel-chart/selection.md
Flutter/funnel-chart/series-customization.md
Flutter/pyramid-chart/callbacks.md
Flutter/pyramid-chart/chart-appearance.md
Flutter/pyramid-chart/datalabel.md
Flutter/pyramid-chart/export-pyramid-chart.md
Flutter/pyramid-chart/getting-started.md
Flutter/pyramid-chart/methods.md
Flutter/pyramid-chart/pyramid-customization.md
Flutter/pyramid-chart/right-to-left.md
Flutter/pyramid-chart/selection.md
Flutter/pyramid-chart/series-customization.md

* Migrate Funnel and Pyramid chart UG with new charts.

FLUT-850998 [Others] Migrate Funnel and Pyramid chart UG with new charts

---

Flutter/circular-charts/annotations.md
Flutter/circular-charts/callbacks.md
Flutter/circular-charts/chart-appearance.md
Flutter/circular-charts/chart-title.md
Flutter/circular-charts/chart-types/doughnut-chart.md
Flutter/circular-charts/chart-types/pie-chart.md
Flutter/circular-charts/circular-series-customization.md
Flutter/circular-charts/datalabel.md
Flutter/circular-charts/export-circular-chart.md
Flutter/circular-charts/getting-started.md
Flutter/circular-charts/legend.md
Flutter/circular-charts/methods.md
Flutter/circular-charts/right-to-left.md
Flutter/circular-charts/tooltip.md

* Migrate Circular chart UG with new charts.

FLUT-852032 [Others] Migrate Circular chart UG with new charts.

---

Flutter/datagrid/filtering.md

Hello,
I have worked on the missing image alt text.
Regards,
Beryl.

SEO-176113-Image-Alt-Text-Flutter2

---

Flutter/pdf/working-with-annotations.md

Hi All,
Added UG documentation for TextMarkup, Popup, and Annotation Flags.
Regards,
Jeyalakshmi T

861628 -UG documentation for TextMarkup, Popup, and Annotation Flags

---

Flutter/cartesian-charts/axis-customization.md
Flutter/cartesian-charts/callbacks.md
Flutter/system-requirements.md

- In this PR, I have updated the visibleMinimum and visibleMaximum properties as initialVisibleMinimum and initialVisibleMaximim. 
- Added the AxisController code snippet for intitalVisibleMinimum, intitalVisibleMaximum, initialZoomFactor and initialZoomPositon properties dynamic update. 
- And added initialIsVisible property dynamic update details in onRendererCreated callback. 
- Updated latest SDK link

FLUT-860220 - [Others] Updated the visibleMinimum and visibleMaximum properties as initialVisibleMinimum and initialVisibleMaximum

---

Flutter/cartesian-charts/axis-customization.md
Flutter/cartesian-charts/callbacks.md
Flutter/system-requirements.md

- In this PR, I have updated the visibleMinimum and visibleMaximum properties as initialVisibleMinimum and initialVisibleMaximim. 
- Added the AxisController code snippet for intitalVisibleMinimum, intitalVisibleMaximum, initialZoomFactor and initialZoomPositon properties dynamic update. 
- And added initialIsVisible property dynamic update details in onRendererCreated callback. 
- Updated latest SDK link

FLUT-862729 - [Others] Updated the visibleMinimum and visibleMaximum properties as initialVisibleMinimum and initialVisibleMaximum

---

Flutter/datagrid/grouping.md
Flutter/datagrid/scrolling.md

- I have add the API links for the completed UG documents.

FLUT-855474- [Others] Added API link for completed features

---

Flutter/system-requirements.md

- In this PR, I have added the line to end the table in the last row.
**Image:**

FLUT-860202 - [Others]  Added the line in the last row of the table

---

Flutter/pdf/working-with-pdf-templates.md

Hi team
I have added the UG documentation sample for Creating templates from existing PDF document in Flutter.
Regards,
Srihariharan G.

864918: Creating templates from existing PDF document in Flutter.

---

Flutter/installation/Installation-errors.md

Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.

SEO-178901-flutter-page-with-redirect-links

---

Flutter/cartesian-charts/chart-types/bar-chart.md

- In this PR, I have updated the missed breaking changes in the track customization part of the bar chart. The ChartSeries has been changed to CartesianSeries.

FLUT-860220 - [Others] Updated the chart series as cartesian series

---

Flutter/system-requirements.md

**Flutter SDK version- 3.16.0 -  Syncfusion version -23.2.5** 
https://github.com/syncfusion-content/flutter-docs/assets/105289202/957a6f8c-2010-4fe8-891c-60e3c36b5fae
**Flutter SDK version- 3.16.0 -  Syncfusion version -24.1.44**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/83d253f9-4bb5-420d-822e-ce580d29fc88
**Flutter SDK version- 3.13.0 -  Syncfusion version -22.2.11**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/c64858d1-3b80-4c8c-ba74-c7da4db6db9a
**Flutter SDK version- 3.13.0 -  Syncfusion version -23.2.4**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/0a89727f-015d-49d2-a03a-ebb87acb2f33
**Flutter SDK version- 3.10.0 -  Syncfusion version -21.2.8**
https://github.com/syncfusion-content/flutter-docs/assets/105289202 …

FLUT-860202 - [Others]  Added the compatible in between syncfusion version for flutter sdk version

---

Flutter/system-requirements.md

- I have updated SDK Version to SDK Version Compatibility.
- I have removed the line above the tabular column.
- I have updated the text alignment to center in the tabular column.
- I have added the latest version link for the Syncfusion Compatible Package version.

FLUT-864900 - [Others]  Updated the latest syncfusion compatible package version and text alignment to center

---

Flutter/system-requirements.md

- I have updated Syncfusion Compatible Package version for 3.16.0 and 3.19.0 Flutter SDK version.
- I have added the latest version link for the Syncfusion Compatible Package version.

FLUT-869469 - [Others]  Updated the latest syncfusion compatible package version

---

Flutter/pdf/working-with-annotations.md
Flutter/pdf/working-with-digital-signature.md

Hi team,
Here we added volume 1 flutter features and bugs for UG documentation.
Regards,
Srihariharan G.

875042: Volume 1 UG documentation in Flutter PDF.

---

Flutter/pdf-viewer/form-filling.md
Flutter/pdf-viewer/getting-started.md
Flutter/pdf-viewer/magnification.md
Flutter/pdf-viewer/undo-redo.md

Added content for 25.1 new features

FLUT-862867-[feature][flutter]: Add content for 25.1 new features

---

Flutter/datagrid/filtering.md
Flutter/datagrid/scrolling.md

- UG documentation for following completed feature :
- [Task 10194](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/10194): Provide the support to set the scroll offset on initial loading of DataGrid
- [Task 868821](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/868821): Support for strongDataType for cell data type that is Comparable.

FLUT-873923 - [Others]: Flutter DataGrid UG for completed features

---

Flutter/themes.md

Added spark theme widget class and their applicable widgets

FLUT-869447 - [Others] Added spark theme widget in user guidelines

---

Flutter/datagrid/filtering.md

- UG documentation for following completed feature :
- [Task 868821](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/868821): Support for strongDataType for cell data type that is Comparable.

FLUT-873923 - [Others]: Flutter DataGrid UG for completed features correction

---

Flutter/calendar/timezone.md

Updated the Vladivostok time zone value to the latest one.
Reference link: https://en.wikipedia.org/wiki/Vladivostok_Time#:~:text=Vladivostok%20Time%20(VLAT)%20(Russian,Time%20(MSK%2B7).

FLUT-880002 - [Others] Modified the Vladivostok time zone value to latest one

---

Flutter/cartesian-charts/methods.md

Added trackball and crosshair behavior hyperlinks of public methods in the user guidelines

FLUT-879684 - [Others] Added behavior hyperlinks in the user guidelines of public methods in hotfix

---

Flutter/cartesian-charts/methods.md

Added trackball and crosshair behavior hyperlinks of public methods in the user guidelines

FLUT-879684 - [Others] Added behavior hyperlinks in the user guidelines of public methods in development

---

Flutter/pdf/working-with-tables.md

Hi team,
Here we resolved the Resolve the URL errors in document processing.
Regards,
Srihariharan G

885092: Resolved the Resolve the URL errors in document processing.

---

Flutter/system-requirements.md

- Updated Syncfusion Compatible Package version for 3.19.0 and 3.22.0 Flutter SDK version.

FLUT-869469 - [Others] Updated the latest syncfusion compatible package version

---

Flutter/pdf-viewer/How-to/Resolve-Library-not-loaded-rpath-libswiftCore-dylib-error.md

Resolved from matter issue

---

Flutter/pdf-viewer/How-to/Resolve-Library-not-loaded-rpath-libswiftCore-dylib-error.md

Resolved front matter issue

---

Flutter/cartesian-charts/annotations.md

- I have updated code snippet for horizontalAlignment  in the CartesianChartAnnotation.
- Code snippet for horizontalAlignment - [Link](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation/horizontalAlignment.html)

FLUT-890165- [Others]  Modified the code snippet for horizontalalignment in the cartesianchart annotation

---

Flutter/cartesian-charts/technical-indicators.md

Added ROC and WMA indicators hyperlinks of public methods in the user guidelines in hotfix

FLUT-879690 - [Others] Added ROC and WMA indicators hyperlinks of public methods in the user guidelines in hotfix

---

Flutter/cartesian-charts/technical-indicators.md

Added ROC and WMA indicators hyperlinks of public methods in the user guidelines in development

FLUT-879690 - [Others] Added ROC and WMA indicators hyperlinks of public methods in the user guidelines in development

---

Flutter/pdf/working-with-digital-signature.md

Hi team,
Here we added UG documentation for LTV and Timestamp - Flutter PDF.
Regards,
Srihariharan G

893607: UG documentation for LTV and Timestamp - Flutter PDF.

---

Flutter/pdf-viewer/getting-started.md

* Added how to load document from base64 content

FLUT-869975 - Added how to load document from base64 content

---

Flutter/cartesian-charts/axis-customization.md

- I have updated the api link for initialVisibleMinimum of NumericAxis in the SfCartesianChart.
- I have updated the api link for initialVisibleMaximum of DateTimeAxis in the SfCartesianChart.
- I have updated the api link for NumericMultiLevelLabel of NumericAxis in the SfCartesianChart.
- I have updated the api link for DateTimeMultiLevelLabel of DateTimeAxis in the SfCartesianChart.
-

FLUT-890165- [Others]  Updated the api link for axis properties in the chart

---

Flutter/pdf-viewer/overview.md

Added overview content for sticky note annotation feature

FLUT-897624: Add sticky note overview

---

Flutter/system-requirements.md

1. Updated the latest Flutter SDK version as 3.24.0 
2. Updayed Syncfusion Compatible Package Version as <25.2.x to 26.2.x(latest)

FLUT-902502 - [Others] Updated the latest Flutter SDK version

---

Flutter/system-requirements.md

- Updated Syncfusion Compatible Package version for 3.22.0 and 3.24.0 Flutter SDK version.

FLUT-903109 - [Others] Updated versions in hotfix

---

Flutter/themes.md

Updated the chat theme file for chart widget.

FLUT-910354 - [Others] Updated the chat theme

---

Flutter/chat/composer.md

Updated the chat widget UG with the below topics page:
- Composer Page

FLUT-910354 - [Others] Updated the chat widget UG

---

Flutter/pdf-viewer/How-to/Add-SignaturePad-signatures-to-Syncfusion-Flutter-PdfViewer.md

* Resolved the compilation error in the code.
* Resolved the issue where the signature appearance is duplicated when flattening all the form fields.
* Cleared the linter warnings in the code.

FLUT-916839: Update sample

---

Flutter/pdf/getting-started.md

Hi All,
Task link:https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/919503
Task name:Need to create a sample in Flutter WASM
Regards,
Sameerkhan N

919503_f1 Save a sample in Flutter WASM

---

Flutter/pdf-viewer/getting-started.md

* Modify the pdf.js script to support wasm compilation

FLUT-925152-[flutter]: Modify content to support wasm

---

Flutter/assistview/overview.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for overview page in assist view widget.
Added:
Changed: …

FLUT-926192 - [Feature] UG docs for overview page in assist view

---

Flutter/assistview/getting-started.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for getting started page in assist view widget.
AssistView theme APIs: All major feature APIs list.
Added: …

FLUT-926192 - [Feature] UG docs for getting started page in assist view

---

Flutter/assistview/placeholder.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for placeholder page in assist view widget.
Added:
Changed: …

FLUT-926192 - [Feature] UG docs for placeholder page in assist view

---

Flutter/assistview/composer.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for composer page in assist view widget.
Added:
Changed: …

FLUT-926192 - [Feature] UG docs for composer page in assist view

---

Flutter/assistview/action-button.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for action button page in assist view widget.
Added:
Changed: …

FLUT-926192 - [Feature] UG docs for action button page in assist view

---

Flutter/assistview/conversation-area.md
Flutter/themes.md
flutter-toc.html

- Implemented UG documentation for conversation area page in assist view widget.
Added:
Changed: …

FLUT-926192 - [Feature] UG docs for conversation area page in assist view

---

Flutter/pdf/getting-started.md
Flutter/pdf/overview.md
Flutter/pdf/working-with-annotations.md
Flutter/pdf/working-with-attachments.md
Flutter/pdf/working-with-bookmarks.md
Flutter/pdf/working-with-digital-signature.md
Flutter/pdf/working-with-document.md
Flutter/pdf/working-with-flow-layout.md
Flutter/pdf/working-with-layers.md
Flutter/pdf/working-with-lists.md
Flutter/pdf/working-with-pdf-conformance.md
Flutter/pdf/working-with-pdf-templates.md
Flutter/pdf/working-with-shapes.md
Flutter/pdf/working-with-tables.md
Flutter/pdf/working-with-text-extraction.md
Flutter/pdf/working-with-text.md
Flutter/pdf/working-with-watermarks.md

Hi All,
Task id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/928117
Task name: Add trademark symbol in Flutter platform
Regards,
Irfana J.

FLUT-928117-[others][flutter]: Added trademark symbol for flutter pdf

---

Flutter/chat/message-content.md
Flutter/chat/overview.md

Added API link for suggestion feature in chat widget.
Added:
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the …

FLUT-927696 - [Feature] Added API link for suggestion feature in chat widget

---

Flutter/calendar/appointments.md
Flutter/calendar/date-navigations.md
Flutter/cartesian-charts/getting-started.md

Updated the published video tutorial samples in user guide on the below pages.
**SfCartesianChart** - How to Create Flutter Charts from JSON Data [[Getting started with Flutter Cartesian Charts widget | Syncfusion](https://help.syncfusion.com/flutter/cartesian-charts/getting-started#bind-data-source)]
**SfCalendar** - How to Display More Appointments in the Flutter Calendar [For this, I thought, we can add in [appointments page.](https://help.syncfusion.com/flutter/calendar/appointments)]
**SfCalendar**  - How to Customize the Date Picker's Appearance in the Flutter Calendar [[Date Navigations in Flutter Event Calendar widget | Syncfusion](https://help.syncfusion.com/flutter/calendar/date-navigations#show-date-picker)]

FLUT-927176 - [Others] Added tutorial samples in user guide

---

Flutter/accessibility.md
Flutter/globalization.md
Flutter/right-to-left.md
Flutter/system-requirements.md
Flutter/themes.md

**accessibility.md**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/70a0a9f8-53c7-4f67-bf7f-6df3890ad171)|![image](https://github.com/user-attachments/assets/18ea04c7-9f53-4a38-bf2e-b91014bcfd3b)|
**globalization.md**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/c81a1e6a-c02c-4da0-a945-ca3f9a34d778)|![image](https://github.com/user-attachments/assets/5cc68de9-3938-4094-af1d-95db5023a3cf)|
|![image](https://github.com/user-attachments/assets/c074d83f-e9ac-46c9-b4a3-7ecdd527ae51)|![image](https://github.com/user-attachments/assets/6c350347-1098-4052-9e28-f0ccdeca4f63)|
**right-to-left.md**
|Before|After|
|--|--| …

FLUT-927176 - [Others] Added trademark symbol for md file

---

Flutter/funnel-chart/getting-started.md
Flutter/funnel-chart/how-to/custom-widget-on-flutterflow.md
Flutter/funnel-chart/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/da4b5c1e-5735-481f-8c41-0694e970501a)|![image](https://github.com/user-attachments/assets/4a707a9b-e751-470e-b8eb-3b54fc825c87)|
|![image](https://github.com/user-attachments/assets/8a8025a7-7302-49d4-8d1f-6b517f88cd80)|![image](https://github.com/user-attachments/assets/00708c92-1055-4e38-843b-482ac956d857)|
|![image](https://github.com/user-attachments/assets/1eeb93a9-c4a1-4b01-83f1-78be2fbd302b)|![image](https://github.com/user-attachments/assets/4c9ffc1e-7fca-4440-b6d8-f62543ea07e2)|
|![image](https://github.com/user-attachments/assets/b03a4a49-8e90-4131-83e0-b7ec06932da7)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for funnel chart

---

Flutter/pyramid-chart/getting-started.md
Flutter/pyramid-chart/how-to/custom-widget-on-flutterflow.md
Flutter/pyramid-chart/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/65c09ceb-37e6-4e32-897b-da738f1b04c0)|![image](https://github.com/user-attachments/assets/2cb989e2-7272-4bfe-9931-c821505f1614)|
|![image](https://github.com/user-attachments/assets/638ce02f-da3a-4bb8-9e32-ae0c0a0b750e)|![image](https://github.com/user-attachments/assets/110125c9-04c7-4287-8854-da1e98a0e5f8)|
|![image](https://github.com/user-attachments/assets/8b6c6e10-aabc-464b-a6dc-19c56fb94023)|![image](https://github.com/user-attachments/assets/60d26087-1ceb-4a83-a1da-aa4d14fe7e15)|
|![image](https://github.com/user-attachments/assets/d3b44332-1099-411e-8545-3a9697daabaf)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for pyramid chart

---

Flutter/ai-assistview/overview.md

**overview-(AssistView)**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/e294760c-846b-47b7-964d-ffbbf0eaf19b)|![image](https://github.com/user-attachments/assets/7f2259d5-a8e1-46c9-b685-1fe84609ec4b)|

FLUT-927176 - [Others] Added trademark symbol for assist view widget

---

Flutter/system-requirements.md

Updated system requirement version for flutter widget.
Added:
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the …

FLUT-931209 - [Feature] Updated system requirement version for flutter widget

---

Flutter/pdf-viewer/form-filling.md

* Added YouTube link in PDFViewer - Form filling

FLUT-932464: Add YouTube link in PDFViewer - Form filling

---

Flutter/pdf-viewer/getting-started.md

* Modified the pdf.js script inclusion content in the PDF Viewer Getting started page.
| Header | Header |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/6111def2-b3e2-47fd-b2a8-12765fd3ac7b) | ![image](https://github.com/user-attachments/assets/82999793-0a29-491d-af7a-b37c36c0ae65)  |

FLUT-930433: Support for newer versions of pdf.js library

---

Flutter/Licensing/overview.md

Cleared conflicts and errors
Added:
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the unit testing written file …

FLUT-932204 - [Feature] Cleared conflicts and errors

---

Flutter/range-selector/range-controller.md

Updated the code snippet for the selection feature in the SfRangeSelector widget in user guide which is suitable for the latest version. 
https://help.syncfusion.com/flutter/range-selector/range-controller#selection-with-sfchart

FLUT-933401 - [Others] Updated selection behavior in range selector

---

Flutter/pdf/getting-started.md
Flutter/pdf/overview.md

Hi All,
Task Id:https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/12946
Tak Name:Add YouTube videos in API doc/ UG
Regards,
Sameerkhan N

12946_ug Added the flutter overview youtube link.

---

Flutter/treemap/drilldown.md

Updated one published YouTube video tutorial sample in user guide for Flutter Treemap in the drilldown features page.
SfTreemap - How to deep dive into the Drilldown Feature in Flutter Treemap?

FLUT-935491 - [Others] Added tutorial samples in ug hotfix

---

Flutter/treemap/drilldown.md

Updated one published YouTube video tutorial sample in user guide for Flutter Treemap in the drilldown features page.
SfTreemap - How to deep dive into the Drilldown Feature in Flutter Treemap?

FLUT-935491 - [Others] Added tutorial samples in ug dev

---

Flutter/DateRangePicker/getting-started.md
Flutter/ai-assistview/getting-started.md
Flutter/barcode/getting-started.md
Flutter/calendar/getting-started.md
Flutter/cartesian-charts/getting-started.md
Flutter/chat/getting-started.md
Flutter/circular-charts/getting-started.md
Flutter/datagrid/getting-started.md
Flutter/funnel-chart/getting-started.md
Flutter/linear-gauge/getting-started.md
Flutter/maps/getting-started.md
Flutter/pdf-viewer/getting-started.md
Flutter/pdf/getting-started.md
Flutter/pyramid-chart/getting-started.md
Flutter/radial-gauge/getting-started.md
Flutter/range-selector/getting-started.md
Flutter/range-slider/getting-started.md
Flutter/signaturepad/getting-started.md
Flutter/slider/getting-started.md
Flutter/sparkcharts/getting-started.md
Flutter/treemap/getting-started.md
Flutter/xlsio/getting-started.md

Updated getting started page links to https://docs.flutter.dev/get-started/test-drive#choose-your-ide for all widgets
Before:
After:

FLUT-935491 - [Others] Updated getting started links in ug hotfix

---

Flutter/DateRangePicker/getting-started.md
Flutter/ai-assistview/getting-started.md
Flutter/barcode/getting-started.md
Flutter/calendar/getting-started.md
Flutter/cartesian-charts/getting-started.md
Flutter/chat/getting-started.md
Flutter/circular-charts/getting-started.md
Flutter/datagrid/getting-started.md
Flutter/funnel-chart/getting-started.md
Flutter/linear-gauge/getting-started.md
Flutter/maps/getting-started.md
Flutter/pdf-viewer/getting-started.md
Flutter/pdf/getting-started.md
Flutter/pyramid-chart/getting-started.md
Flutter/radial-gauge/getting-started.md
Flutter/range-selector/getting-started.md
Flutter/range-slider/getting-started.md
Flutter/signaturepad/getting-started.md
Flutter/slider/getting-started.md
Flutter/sparkcharts/getting-started.md
Flutter/treemap/getting-started.md
Flutter/xlsio/getting-started.md

Updated getting started page links to https://docs.flutter.dev/get-started/test-drive#choose-your-ide for all widgets
Before:
After:

FLUT-935491 - [Others] Updated getting started links in ug dev

---

Flutter/cartesian-charts/on-demand-loading.md
Flutter/treemap/drilldown.md

- I have added the YouTube video tutorial link for on demand loading feature in SfCharts UG documentation.
Video tutorial ID: GBKB1U-iwqI
Video tutorial title: How to Lazy Load Data While Panning in the Flutter Charts?
Video tutorial link: https://www.youtube.com/embed/GBKB1U-iwqI
- I have updated the drill down feature YouTube video tutorial ID in SfTreemaap UG documentation.
Previous video tutorial ID: 1xXeIedJ3bQ
current video tutorial ID: tLAPEDlhfS4
Video tutorial link: https://www.youtube.com/embed/tLAPEDlhfS4

FLUT-928882 - [Others] Added YouTube video tutorial link for SfCharts and updated video tutorial ID for SfTreemap in UG documentation

---

Flutter/maps/shape.md

- I have added the YouTube video tutorial link for apply color based on the data feature in SfMaps UG documentation.
Video tutorial ID: cHEbMFm3TMU
Video tutorial title: how to customize the colors in Flutter Maps?
Video tutorial link: https://www.youtube.com/embed/cHEbMFm3TMU

FLUT-928882 - [Others] Added YouTube video tutorial link for SfMaps in UG documentation 

---

Flutter/maps/shape.md

- I have added the YouTube video tutorial link for apply color based on the data feature in SfMaps UG documentation.
Video tutorial ID: cHEbMFm3TMU
Video tutorial title: how to customize the colors in Flutter Maps?
Video tutorial link: https://www.youtube.com/embed/cHEbMFm3TMU

FLUT-928882 - [Others] Added YouTube video tutorial link for SfMaps UG documentation 

---

Flutter/datagrid/export-to-pdf.md
Flutter/datagrid/getting-started.md
Flutter/datagrid/overview.md

- Added the trademark symbol to the term 'Syncfusion' in the Overview, Getting Started, and Export to PDF files.

FLUT-871331 - [Others] Adding Trade Mark Symbol  

---

Flutter/pdf-viewer/getting-started.md

* Removed the unnecessary code in the pdf.js script code snippet
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/b6793031-e7f4-4bcb-a750-fb15d9a053f2) | ![image](https://github.com/user-attachments/assets/dbf867ff-e3bf-4da2-9dcf-774d1a691f35) |

FLUT-939709: Remove unnecessary code in the pdf.js script code snippet

---

Flutter/maps/shape.md

- I have updated the YouTube video tutorial link section indie the apply color based on the data feature in SfMaps UG documentation.

FLUT-928882 - [Others] Updated YouTube video tutorial link section for SfMaps in UG documentation 

---

Flutter/cartesian-charts/annotations.md

I have updated the property casing.

FLUT-941422 - [Others] Cleared casing issue

---

Flutter/datagrid/sorting.md

- Modified the title size of 'Callbacks' in Sorting.

FLUT-947106 - [Others]: New Feature Documentation 

---

Flutter/datagrid/column-types.md
Flutter/datagrid/placeholder.md
Flutter/datagrid/sorting.md

- API reference links have been added for the new features.

FLUT-947106 - [Others]: Added API Reference Links

---

Flutter/ai-assistview/action-button.md
Flutter/ai-assistview/ai-assistview-theme.md
Flutter/ai-assistview/composer.md
Flutter/ai-assistview/conversation-area.md
Flutter/ai-assistview/getting-started.md
Flutter/ai-assistview/placeholder.md
Flutter/chat/action-button.md
Flutter/chat/chat-theme.md
Flutter/chat/composer.md
Flutter/chat/conversation-area.md
Flutter/chat/getting-started.md
Flutter/chat/placeholder.md
flutter-toc.html

I have updated the content corrections in the Flutter UG documentation.

FLUT-947290 - [others] Updated the content corrections in the Flutter UG documentation Hotfix

---

Flutter/ai-assistview/action-button.md
Flutter/ai-assistview/ai-assistview-theme.md
Flutter/ai-assistview/composer.md
Flutter/ai-assistview/conversation-area.md
Flutter/ai-assistview/getting-started.md
Flutter/ai-assistview/placeholder.md
Flutter/chat/action-button.md
Flutter/chat/chat-theme.md
Flutter/chat/composer.md
Flutter/chat/conversation-area.md
Flutter/chat/getting-started.md
Flutter/chat/placeholder.md
flutter-toc.html

I have updated the content corrections in the Flutter UG documentation

FLUT-947290 - [others] Updated the content corrections in the Flutter UG documentation

---

Flutter/ai-assistview/ai-assistview-theme.md
Flutter/ai-assistview/composer.md
Flutter/ai-assistview/conversation-area.md
Flutter/ai-assistview/getting-started.md
Flutter/chat/action-button.md
Flutter/chat/composer.md
Flutter/chat/conversation-area.md
Flutter/chat/getting-started.md

I have updated the missed and improper highlighted property in code snippet for Chat and AssistView UG documentation

FLUT-947290 - [Others] Updated the missed and improper highlighted property in code snippet for Chat and AssistView UG documentation

---

Flutter/chat/chat-theme.md
flutter-toc.html

I have updated the issue in flutter toc file to update the proper link for assist view how to section in UG documentation.

FLUT-949859 - [Others] Updated the issue in Flutter UG documentation

---

Flutter/introduction/overview.md

Task Link - [[FLUT-953870]](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/953870/)
Removed macOS app center link from the overview page. 
Update the SDK version as ^3.7.0 from ^3.7.0-0
If there is an external design, link to their project documentation area.
If there is an internal discussion on the Forum, provide the link.
Before Removing link:
After Removing link:
List out the areas affected by your code changes.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If there is no TDD (if its not possible to follow), provide the UI automation script location and the Excel file that contains the use cases considered in this implementation.
Provide the …

FLUT-949988 - [Feature] Removed macOS app center link dev

---

Flutter/cartesian-charts/zoom-pan.md

Updated API link for enable directional zooming in UG.

FLUT-966444 - [Others] Updated API link for enable directional zooming

---

Flutter/barcode/accessibility.md
Flutter/barcode/barcode-customization.md
Flutter/barcode/getting-started.md
Flutter/barcode/one-dimensional.md
Flutter/barcode/two-dimensional.md

The task requires a comprehensive review and updating of the documentation for the Barcode generator widget in the "syncfusion_flutter_barcode" Flutter package. The key goals include ensuring all public APIs are documented, verifying the presence of hyperlinks, default values for properties, and trademark information, as well as correcting any misinformation.
- Task ID - https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/965289/
- Review all public APIs in the Barcode generator widget to confirm they are documented.
- Identify any undocumented APIs and prepare descriptions and usage examples for them.
- Check all APIs in the documentation for proper hyperlink inclusion. This ensures developers can easily reference more detailed information.
- Make sure all …

FLUT-965289 - [Feature] Updated ug pages for barcode widget in hotfix branch.

---

Flutter/linear-gauge/bar-pointer.md
Flutter/system-requirements.md

Updated Flutter SDK version compatibility in user guide - https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

FLUT-971736 - [Others] Updated Flutter SDK version compatibility in user guide

---

Flutter/system-requirements.md

Updated Flutter SDK version compatibility in user guide - https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

FLUT-979460 - [Others] Updated Flutter SDK version compatibility in user guide

---

Flutter/datagrid/column-types.md

- Removed repeated lines from the UG - Column Types page

FLUT-972183 - [Others] Updated UG
