syncfusion-content/flutter-docs

Flutter/maps/vector-layers/arc-layer.md

Due to Flutter 3.0.0 update, the animation sample of maps is outdated.(https://help.syncfusion.com/flutter/maps/vector-layers/arc-layer#animation). On that sample codes, I have done the below changes,
-  The animation type (Changed `late Animation animation` as `late Animation<double> animation`)
- Used `TickerStateProviderMixin` with state class because of the usage of `async` in animation.

FLUT-6532 - [Others] Fixed the map animation sample issue

---

Flutter/pdf/getting-started.md
Flutter/pdf/working-with-annotations.md
Flutter/pdf/working-with-attachments.md
Flutter/pdf/working-with-bookmarks.md
Flutter/pdf/working-with-digital-signature.md
Flutter/pdf/working-with-forms.md
Flutter/pdf/working-with-layers.md
Flutter/pdf/working-with-pdf-conformance.md
Flutter/pdf/working-with-pdf-templates.md
Flutter/pdf/working-with-security.md
Flutter/pdf/working-with-watermarks.md

Hi All, 
I have revamp the code snippet in Flutter PDF UG documentation and please find the changes from below, 
- Added the **await** keyword before saving the PDF document. 
**Topics:** 
- Bookmarks 
- Watermarks 
- PDF Template 
- Annotation 
- Security 
- Digital Signature 
- Text extraction 
- PDF Conformance 
- Attachments 
- Layers 
- Getting Started 
- Modified the method name "getApplicationSupportDirectory" instead of "getApplicationDocumentsDirectory".
Kindly review the changes and let me know your feedback for the same. 
Regards,
Sowmiya L

FLUT-6977 - Revamp the code snippet in Flutter PDF UG documentation - Hotfix

---

Flutter/system-requirements.md

- In this PR, I have included the  Flutter SDK version along with its corresponding compatible version for the below controls.
1. Chart.
2. SfMaps.
3. SfTreemap.
4. SfSlider.
5. SfRangeSlider.
6. SfLinearGauge.
7. SfRadialGauge.
8. SfCalendar.
9. SfBarcode.
10. SfSignaturePad.
11. Excel.
12. Pdf.
13. SfDatagrid.
- I have included Windows 11 in the list of operating systems.
**Our widget version - 23.2.5
Flutter SDK version - 3.16.0** 
https://github.com/syncfusion-content/flutter-docs/assets/105289202/c33043c1-1f65-441d-b7dc-ae40f092aca0
**Our widget version - 22.2.11
Flutter SDK version - 3.13.0**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/b7b9f396-e48f-4ba4-a8ea-2b055ab660d4
**Our widget version - 21.2.8
Flutter SDK version - 3.10.0** …

FLUT-860202 - [Others]  Included the SDK with its compatible version

---

Flutter/system-requirements.md

**Flutter SDK version- 3.16.0 -  Syncfusion version -23.2.5** 
https://github.com/syncfusion-content/flutter-docs/assets/105289202/957a6f8c-2010-4fe8-891c-60e3c36b5fae
**Flutter SDK version- 3.16.0 -  Syncfusion version -24.1.44**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/83d253f9-4bb5-420d-822e-ce580d29fc88
**Flutter SDK version- 3.13.0 -  Syncfusion version -22.2.11**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/c64858d1-3b80-4c8c-ba74-c7da4db6db9a
**Flutter SDK version- 3.13.0 -  Syncfusion version -23.2.4**
https://github.com/syncfusion-content/flutter-docs/assets/105289202/0a89727f-015d-49d2-a03a-ebb87acb2f33
**Flutter SDK version- 3.10.0 -  Syncfusion version -21.2.8**
https://github.com/syncfusion-content/flutter-docs/assets/105289202 …

FLUT-869469 - [Others]  Added the compatible in between syncfusion version for flutter sdk version

---

Flutter/pdf-viewer/text-selection.md

- Annotations not applied for the selected text lines in the PDF from the custom text selection context menu.
- Included the pdfViewer key which was missed in the sfpdfviewer widget to resolve this error.

FLUT-921064 - [PDF Viewer] Correction in custom text selection context menu code sample.

---

Flutter/barcode/getting-started.md
Flutter/barcode/how-to/custom-widget-on-flutterflow.md
Flutter/barcode/one-dimensional.md
Flutter/barcode/overview.md

**how-to(Barcode)**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/34ba988c-e6b7-46e8-a586-d62749642da1)|![image](https://github.com/user-attachments/assets/ee47fa63-20c9-4f08-be63-7915fe1d33ae)|
|![image](https://github.com/user-attachments/assets/2be6eaa5-f237-45c3-8699-03911a0692d9)|![image](https://github.com/user-attachments/assets/fec6a275-554a-4b8e-938b-ac96d1ba39fe)|
|![image](https://github.com/user-attachments/assets/c835c150-baf9-4ce9-b7ab-2e914b5fa914)|![image](https://github.com/user-attachments/assets/ba12287b-6a02-441b-bffd-db92b82bb900)|
|![image](https://github.com/user-attachments/assets/f1acf1fc-aacc-4e30-84af-59047d6479a7)|![image] …

FLUT-927176 - [Others] Added trademark symbol for barcode widget

---

Flutter/cartesian-charts/accessibility.md
Flutter/cartesian-charts/charts-type.md
Flutter/cartesian-charts/getting-started.md
Flutter/cartesian-charts/how-to/custom-widget-on-flutterflow.md
Flutter/cartesian-charts/overview.md

**how-to(Cartesian Chart)**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/aca3358c-9f73-4d3d-ae9a-bb6328063507)|![image](https://github.com/user-attachments/assets/edf0ffb7-49c8-4060-a7f8-bc37943bd2e0)|
|![image](https://github.com/user-attachments/assets/4165a5b7-a5bd-4a92-ad77-fd6af4035402)|![image](https://github.com/user-attachments/assets/d42681ce-1e31-41b4-8c78-ccb8b19db710)|
|![image](https://github.com/user-attachments/assets/e07a0307-491a-4e10-9a33-a3ab90c0148d)|![image](https://github.com/user-attachments/assets/8d2ef2c0-3177-4ce4-8bc3-d4b48a3bcafa)|
|![image](https://github.com/user-attachments/assets/c1f50546-6ddd-4011-9f7f-5fd5bc8233d6)| …

FLUT-927176 - [Others] Added trademark symbol for cartesian chart

---

Flutter/circular-charts/charts-type.md
Flutter/circular-charts/getting-started.md
Flutter/circular-charts/how-to/custom-widget-on-flutterflow.md
Flutter/circular-charts/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/254e50ec-70e0-4201-aa6d-fa616ce52117)|![image](https://github.com/user-attachments/assets/218513e8-59f5-490e-9bdb-74c4ad5f2dc6)|
|![image](https://github.com/user-attachments/assets/7e969a5b-7a12-42bd-a3a6-45c5543da181)|![image](https://github.com/user-attachments/assets/ce39c658-c7d3-47c6-b39a-e7ae9dc3db02)|
|![image](https://github.com/user-attachments/assets/95b8741c-6580-4a23-bf33-74495f5e638f)|![image](https://github.com/user-attachments/assets/e0e7f576-504a-459b-addc-1b96eb20c82a)|
|![image](https://github.com/user-attachments/assets/4c1b89bd-e3a7-4308-b1e2-2e2670d9325c)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for circular chart

---

Flutter/Licensing/overview.md
Flutter/introduction/api-reference.md
Flutter/introduction/overview.md
Flutter/introduction/widgets-catalog.md

**Introduction**
**api-reference**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/c8e38766-4d1b-4b2a-a64e-d2e3843790a2)|![image](https://github.com/user-attachments/assets/ca11c970-21f3-461e-b1f7-0a465ef327d2)|
**overview**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/55dd5c3a-fc09-4179-8586-31b49497e3e8)|![image](https://github.com/user-attachments/assets/db8f799d-b73f-41d5-9e6c-f4e86095ec87)|
**widget-catalog**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/a88135ae-6399-45c8-9d0c-76db563c03dd)|![image](https://github.com/user-attachments/assets/af44f4cb-4153-4e4b-8c29-a572e24423ff)| …

FLUT-927176 - [Others] Added trademark symbol for introduction and licensing

---

Flutter/linear-gauge/getting-started.md
Flutter/linear-gauge/how-to/custom-widget-on-flutterflow.md
Flutter/linear-gauge/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/05c6002f-499d-406b-8571-8fd39e890789)|![image](https://github.com/user-attachments/assets/058b303c-dedd-4958-9c67-42d625775f82)|
|![image](https://github.com/user-attachments/assets/ad3a64b3-478d-4455-8cfb-914221be8118)|![image](https://github.com/user-attachments/assets/2ee01155-2d20-49fa-9cef-6d3a15ccfa09)|
|![image](https://github.com/user-attachments/assets/5f9ea5ac-b6bf-4d8f-a8ff-d9245e489463)|![image](https://github.com/user-attachments/assets/13fe49ee-a2ca-44c6-80d1-4ab0640cfb4f)|
|![image](https://github.com/user-attachments/assets/8171aa8a-2c32-40dd-abeb-515916d77802)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for linear gauge

---

Flutter/radial-gauge/getting-started.md
Flutter/radial-gauge/how-to/custom-widget-on-flutterflow.md
Flutter/radial-gauge/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/7fcc9e0b-b7bf-4f15-8d71-b5eceb2784d6)|![image](https://github.com/user-attachments/assets/51b5432e-8db3-49e6-a143-9fce0e3e3bb3)|
|![image](https://github.com/user-attachments/assets/d7eb443d-f9d4-47aa-b102-8ef9d3301ccb)|![image](https://github.com/user-attachments/assets/631703fe-eef2-45b5-8424-f7597ee01129)|
|![image](https://github.com/user-attachments/assets/31db60c0-5836-45d4-a98a-795a80bc9c37)|![image](https://github.com/user-attachments/assets/6895a235-2ad1-4619-94cf-fef1204afe00)|
|![image](https://github.com/user-attachments/assets/cac9bd37-6655-4f0f-94b1-f2150336edfe)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for radial gauge

---

Flutter/maps/getting-started.md
Flutter/maps/how-to/custom-widget-on-flutterflow.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/c6f03921-835c-4738-9fe6-4feadbbd5898)|![image](https://github.com/user-attachments/assets/d5a9a915-c625-4fe7-a886-cc3649c345d0)|
|![image](https://github.com/user-attachments/assets/77dfb487-42c7-486a-85b4-30652d8a9178)|![image](https://github.com/user-attachments/assets/c30af46f-5628-481d-869d-c93ecc620847)|
|![image](https://github.com/user-attachments/assets/e450640e-6b2e-4e00-85d8-0ffe833ca0c8)|![image](https://github.com/user-attachments/assets/692af540-5877-4830-8280-bff206f4110f)|
|![image](https://github.com/user-attachments/assets/2d424336-64b3-471b-9235-eacf7749aaf1)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for maps

---

Flutter/DateRangePicker/getting-started.md
Flutter/DateRangePicker/how-to/custom-widget-on-flutterflow.md
Flutter/DateRangePicker/overview.md

**how-to**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/1f7ba131-2c42-4118-83a5-f61654d262a8)|![image](https://github.com/user-attachments/assets/4dc947c0-5c9c-4bfd-9ff9-18bc09af02cc)|
|![image](https://github.com/user-attachments/assets/01dc87f3-d518-4725-8452-1bd34150805c)|![image](https://github.com/user-attachments/assets/d90b1bee-8733-43b6-993c-7efc24eb8273)|
|![image](https://github.com/user-attachments/assets/7ab7ed3d-d0c9-466e-8e89-bea7ce41f174)|![image](https://github.com/user-attachments/assets/0612828c-b3d2-464b-b3f7-9e73eec768f6)|
|![image](https://github.com/user-attachments/assets/2b827c5f-9451-48a6-885b-e028a27d32d4)|![image](https:// …

FLUT-927176 - [Others] Added trademark symbol for date range picker

---

Flutter/calendar/getting-started.md
Flutter/calendar/how-to/custom-widget-on-flutterflow.md
Flutter/calendar/overview.md

**how-to(Calendar)**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/af02d08d-129a-44c6-8401-e9d36c0125ac)|![image](https://github.com/user-attachments/assets/a6ad41e9-a747-45de-92e1-49dedeb99cfb)|
|![image](https://github.com/user-attachments/assets/2eda966c-2e29-4506-b168-657b95007ecd)|![image](https://github.com/user-attachments/assets/bba0802f-942a-401f-adc0-98402815ad6e)|
|![image](https://github.com/user-attachments/assets/010b6863-8630-4234-b994-a8269f9f0ff7)|![image](https://github.com/user-attachments/assets/e20b6a48-d0d2-4ee1-ba4e-6af745724b9b)|
|![image](https://github.com/user-attachments/assets/ff53bf1c-0b12-40d1-9c3f-f735d4d3d849)|![image …

FLUT-927176 - [Others] Added trademark symbol for calendar widget

---

Flutter/chat/overview.md

**overiew**
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/c745cc13-f0c6-4150-8808-1134f228b5e0)|![image](https://github.com/user-attachments/assets/f7db1a97-4b44-4ef2-acc6-19c86d3d8044)|

FLUT-927176 - [Others] Added trademark symbol for chat

---

Flutter/slider/basic-features.md
Flutter/slider/getting-started.md
Flutter/slider/labels-and-divider.md

Updated one published YouTube video tutorial sample in user guide for Flutter Slider in the basic features page.
**SfSlider** - How to customize thumb and divider in Flutter Slider?
Also modified the heading text in the Labels and Divider file as the title of this respective section is wrong. Instead of Slider, it is mentioned as Treemap.
**Before:**
**After:**

FLUT-927176 - [Others] Added tutorial samples in user guide

---

Flutter/pdf-viewer/form-filling.md

* Resolved the YouTube link error in the PDF viewer form filling page.

FLUT-932464: Resolve the youtube link issue

---

Flutter/maps/shape.md

- I have updated the YouTube video tutorial link section indie the apply color based on the data feature in SfMaps UG documentation.

FLUT-928882 - [Others] Updated YouTube video tutorial link section for SfMaps in UG documentation

---

Flutter/datagrid/column-types.md
Flutter/datagrid/placeholder.md
Flutter/datagrid/sorting.md

- API reference links have been added for the new features.

FLUT-947106 - [Others]: Added API Reference Links

---

Flutter/ai-assistview/ai-assistview-theme.md
Flutter/ai-assistview/composer.md
Flutter/ai-assistview/conversation-area.md
Flutter/ai-assistview/getting-started.md
Flutter/chat/action-button.md
Flutter/chat/composer.md
Flutter/chat/conversation-area.md
Flutter/chat/getting-started.md

I have updated the missed and improper highlighted property in code snippet for Chat and AssistView UG documentation

FLUT-947290 - [Others] Updated the missed and improper highlighted property in code snippet for Chat and AssistView UG documentation

---

Flutter/introduction/overview.md

Task Link - [[FLUT-953870]](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/953870/)
Removed macOS app center link from the overview page. 
Update the SDK version as ^3.7.0 from ^3.7.0-0
If there is an external design, link to their project documentation area.
If there is an internal discussion on the Forum, provide the link.
Before Removing link:
After Removing link:
List out the areas affected by your code changes.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If there is no TDD (if its not possible to follow), provide the UI automation script location and the Excel file that contains the use cases considered in this implementation.
Provide the …

FLUT-949988 - [Feature] Removed macOS app center link hotfix

---

Flutter/ai-assistview/composer.md
Flutter/ai-assistview/how-to/custom-widget-on-flutterflow.md
Flutter/ai-assistview/right-to-left.md
Flutter/chat/action-button.md
Flutter/chat/chat-theme.md
Flutter/chat/composer.md
Flutter/chat/conversation-area.md
Flutter/chat/getting-started.md
Flutter/chat/how-to/custom-widget-on-flutterflow.md
Flutter/chat/overview.md
Flutter/chat/placeholder.md
Flutter/chat/right-to-left.md

- Task Link - [[FLUT-958974]](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/958974/), [[FLUT-958970]](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/958970/)
- Need to clear grammatical issues, paraphrasing for both Chat and AIAssist View widget. 
- Need to correct the grammatical mistakes for above mentioned Chat Section in the Flutter User Guide documentation widget by using the Syncfusion Continue AI.
Copy the UG content with code snippet and modify it in Continue AI based on the shared prompt. Modify the shared prompt based on your needs if needed.
Replace the hyperlink given by the AI with the original hyperlink.
Ensure naming casing of the widget.
Replace the existing code snippet alignment with AI code snippet in proper …

FLUT-956087 - [Feature] Cleared grammatical issues for chat and assistview

---

Flutter/barcode/accessibility.md
Flutter/barcode/barcode-customization.md
Flutter/barcode/getting-started.md
Flutter/barcode/one-dimensional.md
Flutter/barcode/overview.md
Flutter/treemap/accessibility.md
Flutter/treemap/color-customization.md
Flutter/treemap/getting-started.md
Flutter/treemap/labels.md
Flutter/treemap/layout.md
Flutter/treemap/legend.md
Flutter/treemap/overview.md
Flutter/treemap/tooltip.md

- Task Link - [[FLUT-958965]](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/958965)
- Need to clear grammatical issues, paraphrasing for both Barcode and Treemap widget. 
- Need to correct the grammatical mistakes for above mentioned Chat Section in the Flutter User Guide documentation widget by using the Syncfusion Continue AI.
Copy the UG content with code snippet and modify it in Continue AI based on the shared prompt. Modify the shared prompt based on your needs if needed.
Replace the hyperlink given by the AI with the original hyperlink.
Ensure naming casing of the widget.
Replace the existing code snippet alignment with AI code snippet in proper alignment.
Prompt:
Use the prompt below for UG review in AI-Continue.
Review the following User Guide(UG) …

FLUT-958965 - [Feature] Cleared grammatical issues for barcode and treemap

---

Flutter/xlsio/overview.md

Hi @MallikaKannan
|Title|Description|
|--|--|
|Task Category|Site Audit- SERPSTAT Help Issue Fixes
|Content Task Link/Mail Screenshot|![image](https://github.com/user-attachments/assets/d4edec1b-b440-4d2d-99b5-6fc21041e90b)![image](https://github.com/user-attachments/assets/ea8a00a4-72ae-4cef-b839-e782b5147c49)|
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/flutter-docs/pull/1227
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/202603
Changes Made | Reason for change |
-- | -- |
|H1 Duplicates title|According to SEO the H1 Should be similar to title in same page|
Regards,
Mercy

202603-Site-Audit-Serpstat-Help-Category-H1-duplicates-title

---

Flutter/barcode/accessibility.md
Flutter/barcode/barcode-customization.md
Flutter/barcode/getting-started.md
Flutter/barcode/one-dimensional.md
Flutter/barcode/two-dimensional.md

The task requires a comprehensive review and updating of the documentation for the Barcode generator widget in the "syncfusion_flutter_barcode" Flutter package. The key goals include ensuring all public APIs are documented, verifying the presence of hyperlinks, default values for properties, and trademark information, as well as correcting any misinformation.
- Task ID - https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/965289/
- Review all public APIs in the Barcode generator widget to confirm they are documented.
- Identify any undocumented APIs and prepare descriptions and usage examples for them.
- Check all APIs in the documentation for proper hyperlink inclusion. This ensures developers can easily reference more detailed information.
- Make sure all …

FLUT-965289 - [Feature] Updated ug pages for barcode widget

---

Flutter/linear-gauge/bar-pointer.md
Flutter/system-requirements.md

Updated Flutter SDK version compatibility in user guide - https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

FLUT-971736 - [Others] Updated Flutter SDK version compatibility in user guide
